await trava a função novamente, temos que tomar cuidado quando chamamos uma funcao que demora para ser executada
